### ISSUE TITLE
Enhancement proposal: Optionally filter projectIDs at scrape-time

### ISSUE THREAD

**Issue by xairos** [prometheus-community/stackdriver_exporter#145]
Thanks for the `stackdriver_exporter` project! This project has allowed us to consolidate metrics in Prometheus, further enabling us to build centralized Prom tooling (ex. for SLOs).

I'm proposing following change:

### Current behaviour

Metrics can be filtered at call-time via the following scrape config:
```yaml
params:
  collect:
  - compute.googleapis.com/instance/cpu
  - compute.googleapis.com/instance/disk
```

### Proposed behaviour

Metrics could be filtered by both projectID and prefix at call-time:
```yaml
params:
  project_ids:
  - my-test-project1
  - my-test-project2
  collect:
  - compute.googleapis.com/instance/cpu
  - compute.googleapis.com/instance/disk
```

### How it could be helpful

For the platform team that I work on, this would enable hosting `stackdriver_exporter` as a service to tenants. The tenants have their own GCP projects, and they could filter for metrics from their own projects at scrape-time.

I'd be happy to contribute this enhancement if it makes sense.
