### ISSUE TITLE
Filtering doesn't seem to work

### ISSUE THREAD

**Issue by akasprzok** [prometheus-community/stackdriver_exporter#191]
Summary:

I can't get metrics filtering to work. My goal is to filter on multiple different user metadata labels, but right now I can't get a single one to work.

Version: v0.12.0

Config (abridged, in a k8s deployment manifest):
```yaml

 spec:
      containers:
      - args:
        - --monitoring.metrics-type-prefixes=cloudsql.googleapis.com/database
        - --monitoring.filters='cloudsql.googleapis.com/database:metadata.user_labels."my-label"="my-value"'
```

Given that config I'd expect the filter to be included in the debug log[ here](https://github.com/prometheus-community/stackdriver_exporter/blob/441c02d01c3b815d2c08c8fb06770cbf8b62ed68/collectors/monitoring_collector.go#L267) but that doesn't seem to be the case. The log statements generally only include the metric.type filter:

```
ts=2023-01-24T06:45:40.496Z caller=monitoring_collector.go:290 level=debug msg="retrieving Google Stackdriver Monitoring metrics with filter" filter="metric.type=\"cloudsql.googleapis.com/database/postgresql/insights/aggregate/execution_time\""
```
and the metrics scraped include metrics from databases not tagged with `my-label=my-value`.

I'm new to GCP, and assume this is just something silly stemming from my lack of familiarity with Stackdriver. Would love any pointers.
